name: rmapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-422.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mysql1: ^0.20.0
  http: ^0.13.5
  requests: ^4.7.0
  flutter_barcode_scanner: ^2.0.0
  pdf: ^3.10.1
  printing: ^5.10.3
  json_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_model: 
  build_runner: ^2.4.4
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  assets:
        - assets/images/
